### ISSUE TITLE
Settings not saving?

### ISSUE THREAD

**Issue by MetaHumanREAL** [MetaHumanREAL/Venge-Client#8]
Someone is saying that the Client Settings aren't saving. Can you investigate this? You can message KAAN (850325063844626443) to try and get error logs/test with him.
![](https://cdn.discordapp.com/attachments/1090994825962209361/1132983893260242995/Screen_Shot_2023-07-24_at_12.33.17.png)

**Comment by MetaHumanREAL** [comment]
I'm thinking maybe we should scrap the idea of having Client Settings inside of the settings area on Venge. We should probably have a separate place for Client Settings so we can 100% save and get all variables for it. When we update the UI, it may mess with it. So using a separate electron window for it seems to be the best option.

Maybe you can figure out a way to make it look like it's in the game, similar to how the old Friend system used to be where it would pop out from the right side of the screen.

@Capta1nCool

**Comment by Capta1nCool** [comment]
updated to side bar.
